name: Test Lint and Compile Workflow

on:
  workflow_dispatch:
    
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Step
        run: npm ci

      - name: Test Step
        run: npm run test

      - name: Linting Step
        run: npm run lint
      
      - name: Test Compile Step
        run: npm run tsc

